### ISSUE TITLE
Icon tags not found

### ISSUE THREAD

**Issue by dest4131** [CodeDaraW/Hacker#10] opened 2016-09-19 08:53 UTC
Hi,
the computed css rule 
`background: url("../../images/icon-tags.svg") center center no-repeat; `
leads to a 404 error. It should be changed to
`background: url("../images/icon-tags.svg") center center no-repeat;`

Observed with both hexo server and hexo static generated files. I use a blog subfolder, with the following configuration:

`menu:`
`  Home: /blog/`
`  Archives: /blog/archives`
`...`

**Comment by CodeDaraW** [comment] 2016-09-22 05:05
I haven't tested with your configuration file.  
It seems that you want to put your site in a subdirectory, but you configured the theme's `_config.yml`.  
You'd better configure the global `_config.yml`:
```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.demo.com/blog
root: /blog/
```

**Comment by dest4131** [comment] 2016-09-22 07:05
Hi CodeDaraW,
The global `__config.yml`  is already configured the way you suggest.
The theme `__config.yml` has also to be configured for blog subfolder (as in OP) otherwise the top "Home" and "Archives" links do not work properly.

In the end, I am a bit lost and the best I could do is to put the "blog" subfolder in both configuration files. Then the only minor broken thing is that `icon-tags.svg` link (as explained in OP). 

I fixed that by altering `source/css/components/icons.styl`

Are there better practises maybe?

I found a solution by myself so you can close this issue if you don't have the time now, but in the future if other users report a similar problem you will know they are not alone.
Thanks for the theme by the way!

**Comment by CodeDaraW** [comment] 2016-09-22 08:45
I'm sorry that it's quite busy at the moment, but I will give you a more elegent solution or the cause before closing the issue. 

Please wait.
 
XD

**Comment by CodeDaraW** [comment] 2016-09-23 08:44
bug fixed. ([update v1.0](https://github.com/CodeDaraW/Hacker/commit/dc4a047cac6f26c47aba7bcd5b36f3ea7d3abf8b))

**Closed by CodeDaraW** 2016-09-23 08:44 UTC
Labels: bug
